### ISSUE TITLE
relative server urls are wrongly considered as error when validating

### ISSUE THREAD

**Issue by Walter-Link** [openapi4j/openapi4j#118] opened 2020-06-30 07:32 UTC
**Describe the bug**
The OpenAPI specification states that the server URL "MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served." But if i validate an OpenAPI spec with relative URL the ServerValidator creates a failure message:

OpenApi3 validation failure
Validation error(s) :
servers.url: Invalid URL '/internal/orderServices/internal/orderServices' (code: 108)
From: servers.url

**To Reproduce**
1. create an API specification having a relative Server url, e.g.
{
  "openapi" : "3.0.0",
  "info" : {
    "description" : "REST Service for order delivery",
    "title" : "REST_deliverOrder",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "/internal/orderServices"
  } ],
  "paths" : {
  "paths" : {
     ......
 }
}
  
2. OpenApi3Validator.instance().validate(model);

**Expected behavior**
I expect the validation to succeed without ValidationException.

**Comment by llfbandit** [comment] 2020-06-30 08:05
Hi,

I confirm the issue, `OAIContext#getBaseUrl` is missing when checking relative url in parser module.

**Comment by llfbandit** [comment] 2020-07-02 10:54
This should be fixed in 1.0.3-SNAPSHOT.

Now server URLs have its own validator.
Other URLs are checked with server URL and context base URL when server URL is relative.

Are you able to validate the changes ?

**Comment by Walter-Link** [comment] 2020-07-08 13:55
Hi,

i tried the new release 1.0.3
Actually my code looks like the following:

OpenApi3 model = createOpenApiModel();

try {
   OpenApi3Validator.instance().validate(model);
} catch (ValidationException e) {
   JErrorDialog.showErrorDialog("export OpenAPI specification",
"validation", e );
   return;
}

Now, when trying to validate my model i got a NullPointerException
Caused by: java.lang.NullPointerException
at
org.openapi4j.parser.validation.v3.ServerValidator.checkServerUrl(ServerValidator.java:94)
at
org.openapi4j.parser.validation.v3.ServerValidator.checkUrlWithVariables(ServerValidator.java:69)
at
org.openapi4j.parser.validation.v3.ServerValidator.validate(ServerValidator.java:37)
at
org.openapi4j.parser.validation.v3.ServerValidator.validate(ServerValidator.java:20)

I then added my own OAIContext:

final URL baseUrl = new URL("http://localhost");
OAIContext context = new OAIContext() {
@Override
public ReferenceRegistry getReferenceRegistry() {
return null;
}
@Override
public URL getBaseUrl() {
return baseUrl;
}
@Override
public JsonNode getBaseDocument() {
return null;
}
};

model.setContext(context);

OpenApi3Validator.instance().validate(model);

That seemed to work, but then, if i serialized the model using the jackson
ObjectMapper the server had a property "defaultUrl" which is not valid in
OpenApi:

{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Rest provider",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "/1023d715-3162-43c3-9bcf-429cd8234378/27",
    *"defaultUrl" : "/1023d715-3162-43c3-9bcf-429cd8234378/27"*
  } ],

So actually the change is not fully sufficient to me.

Best Regards,

Walter




Am Do., 2. Juli 2020 um 12:54 Uhr schrieb llfbandit <
notifications@github.com>:

**Comment by llfbandit** [comment] 2020-07-08 16:23
Since you don't provide a reproducer, I can't help you further.
I don't know from where you come with `createOpenApiModel` method.
Are you building your own api model from it?
You must not create the context by yourself, this done by 'parse' method and attached to `OpenApi3` model internally.

You should load your API description and validate it like this:
```java
OpenApi3 api = new OpenApi3Parser().parse(<URL>, false); // true to validate it directly
OpenApi3Validator.instance().validate(api);
```

That said, I note the bug with `getDefaultUrl` exclusion from serialisation.
Also, you should call toNode/toString methods for this need instead of re-creating `ObjectMapper` or you will have other troubles.

**Comment by Walter-Link** [comment] 2020-07-10 06:10
Actually my task is to export an OpenApi specification from Rest interfaces
defined in our software. So i build the model with your Api:

public OpenApi3 createOpenApiModel() {
    OpenApi3 model = new OpenApi3();
    model.setOpenapi("3.0.0");
    info = new Info();
    info.setVersion(<version>);
    info.setTitle(<title>);
    model.setInfo(info);

    Server server = new Server();
    server.setUrl(<relativeUrl>);
    model.addServer(server);
    ....
    return model;
}

Then i validate the model

OpenApi3Validator.instance().validate(model);

and serialize it into a Json or Yaml file

OutputStream outStream = new FileOutputStream( <file> );
ObjectMapper mapper = <requestYaml> ? TreeUtil.yaml : TreeUtil.json;
ObjectWriter writer = mapper.writerWithDefaultPrettyPrinter();
writer.writeValue(gen, model);

So from my point of view it should be possible to simply set a relative
server URL in the build model and validation should succeed.

Best regards,

Walter Link


Am Mi., 8. Juli 2020 um 18:23 Uhr schrieb llfbandit <
notifications@github.com>:

**Comment by Walter-Link** [comment] 2020-07-10 06:46
So if you need to reproduce the error, here is  a simple test program:

public static final void main (String[] args) throws Exception {
OpenApi3 model = new OpenApi3();
model.setOpenapi("3.0.0");
Info info = new Info();
info.setVersion("1.0");
info.setTitle("my model");
model.setInfo(info);

Server server = new Server();
server.setUrl("/my/service");
model.addServer(server);

Path pathResource = new Path();
pathResource.setSummary("test resource");
model.setPath("/test/{itemid}", pathResource);
Operation operation = new Operation();
Parameter itemId = new Parameter();
itemId.setName("itemid");
itemId.setIn("path");
itemId.setRequired(true);

operation.setSummary("get item data");
List<Parameter> parameters = new ArrayList<> ();
parameters.add(itemId);
operation.setParameters(parameters);
Response successResponse = new Response();
successResponse.setContentMediaType("text/xml", new MediaType());
successResponse.setDescription("success response");
operation.setResponse("200", successResponse);
pathResource.setOperation("get", operation);

OpenApi3Validator.instance().validate(model);
}

Best regards,

Walter Link

Am Fr., 10. Juli 2020 um 08:10 Uhr schrieb Walter Link <
walter.link.aha@gmail.com>:

**Comment by llfbandit** [comment] 2020-07-10 06:59
Thanks for the clarification.

Relative URLs can only exist if there is a base.
In OAI, all URLs can be relative to server Url and itself relative to the base document. 
In your case, you have none. To fix this you must attach a context with a valid base URL to your api model with setContext(OAI3Context).

**Closed** 2020-07-16 09:12 UTC
Labels: bug
