### ISSUE TITLE
External references via $ref not present in OpenApiParser

### ISSUE THREAD

**Issue by smhc** [openapi4j/openapi4j#70] opened 2020-03-17 05:55 UTC
**Describe the bug**
A spec file that references another via $ref will validate the contents of the referenced spec file, but will not integrate the content into the final parser for use .

**To Reproduce**

A file "openapi.json" that references another via path:
```json
  "paths": {
    "/pet/{id}": {
        "$ref": "other.json#/paths/~1pet~1{id}"
     }
```

And another file "other.json":
```json
  "paths": {
    "/pet/{id}": {
        "get": {
               etc
         }
     }
```

Then attempt to validate a request against the path.

```java
        //    api = new OpenApi3Parser().parse("openapi.json");
        Path path = api.getPath("/pet/{id}");
        Operation op = path.getOperation("get");
        // error - method "get" not found
```

**Expected behavior**
Expect to be able to use the "root" spec file that references other spec files to transparently validate data as though everything was defined in the "root" spec file.

**Additional context**
I can verify the referenced file is loaded and validated as part of parsing. Errors in the referenced file are detected correctly. However the contents referenced under the path are only available as the original string reference via the 'ref' property.

**Comment by llfbandit** [comment] 2020-03-17 08:38
Hi,

This is not a bug report and parser module won't change the way the Document has been described.

If you need to get the content of a $ref, you have two ways:
- `[model].getReference(context).getMappedContent(clazz.class);` 
- `[model].copy(context, true);`

**Comment by smhc** [comment] 2020-03-17 10:41
Thank you, the following worked for me;

```java
        Path path = api.getPath(urlPath);
        Operation op = null;
        if (path.isRef()) {
            op = path.copy(api.getContext(), true).getOperation(method);
        }
        else {
            op = path.getOperation(method);
        }
        validator = new OperationValidator(validationContext, api, path, op);

        validator.validateBody..etc
```

I found it was necessary to use the original 'path' when creating the 'OperationValidator'.

If path itself wasn't a ref, but had parameters that referenced schemas in other files, would the above still work ok? Do you have to do a recursive check through your model looking for a 'isRef' to ensure you have a working validator?

**Comment by llfbandit** [comment] 2020-03-17 11:08
Yes, it should work for variables in path as the registry is available from the context.
Internally, `OperationValidator` makes flat all the description for the current operation to simplify the process and keep best performance for each further request/response.

**Comment by smhc** [comment] 2020-03-17 11:28
Great, thanks. I'll close the issue.

**Comment by smhc** [comment] 2020-04-06 06:14
I've been experimenting with this setup and the use of discriminators. It seems the "path.copy" does not perform a deep copy when it comes to discriminators. i.e the example listed at: "https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/" does not work if it is in another file,  referenced via $ref for a path. It does work if it is the 'main' file however.

An exception is thrown when trying to construct the 'OperationValidator'.

Could there be a workaround to this problem?


```
java.lang.NullPointerException
        at org.openapi4j.schema.validator.v3.ReferenceValidator.<init>(ReferenceValidator.java:47)
        at org.openapi4j.schema.validator.v3.ValidatorsRegistry.getValidators(ValidatorsRegistry.java:65)
        at org.openapi4j.schema.validator.v3.SchemaValidator.read(SchemaValidator.java:171)
        at org.openapi4j.schema.validator.v3.SchemaValidator.<init>(SchemaValidator.java:86)
        at org.openapi4j.schema.validator.v3.DiscriminatorValidator.setupAnyOneOfDiscriminatorSchemas(DiscriminatorValidator.java:164)
        at org.openapi4j.schema.validator.v3.DiscriminatorValidator.setupDiscriminator(DiscriminatorValidator.java:114)
        at org.openapi4j.schema.validator.v3.DiscriminatorValidator.<init>(DiscriminatorValidator.java:54)
        at org.openapi4j.schema.validator.v3.OneOfValidator.<init>(OneOfValidator.java:34)
        at org.openapi4j.schema.validator.v3.ValidatorsRegistry.getValidators(ValidatorsRegistry.java:65)
        at org.openapi4j.schema.validator.v3.SchemaValidator.read(SchemaValidator.java:171)
        at org.openapi4j.schema.validator.v3.SchemaValidator.<init>(SchemaValidator.java:86)
        at org.openapi4j.schema.validator.v3.SchemaValidator.<init>(SchemaValidator.java:63)
        at org.openapi4j.operation.validator.validation.BodyValidator.initValidator(BodyValidator.java:69)
        at org.openapi4j.operation.validator.validation.BodyValidator.<init>(BodyValidator.java:35)
        at org.openapi4j.operation.validator.validation.OperationValidator.createBodyValidators(OperationValidator.java:374)
        at org.openapi4j.operation.validator.validation.OperationValidator.createResponseBodyValidators(OperationValidator.java:360)
        at org.openapi4j.operation.validator.validation.OperationValidator.<init>(OperationValidator.java:134)
        at org.openapi4j.operation.validator.validation.OperationValidator.<init>(OperationValidator.java:86)
        at xxxxx.createValidator(xxx)
```

**Comment by llfbandit** [comment] 2020-04-06 11:57
Can you provide a reproducer?
If the reference content is reachable and validated at parsing time this should work.
Also, did you provide the same OAIContext to the OperationValidator?

**Comment by smhc** [comment] 2020-04-06 13:48
The root openapi.json file simply refers to the one above;

```json
{
  "openapi": "3.0.3",
  "info": {
    "description": "openapi test spec",
    "title": "xxx",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:80/api"
    }
  ],
  "paths": {
    "/v1/xxxx": {
      "$ref": "other_file.yaml#/paths/~1v1~1xxxx"
    }
  }
}
```

The code is more or less;

```json
        Path path = api.getPath(urlPath);
        Operation op = null;
        if (path.isRef()) {
            op = path.copy(validationContext.getContext(), true).getOperation(method);
        }
        else {
            op = path.getOperation(method);
        }
        validator = new OperationValidator(validationContext, api, path, op);
        validator.validateBody..etc
```

I believe I am passing the same context through.

**Comment by llfbandit** [comment] 2020-04-06 14:32
copy method of a schema will never copy flatten content for collections schemas when there's a discriminator since it only works with referenced schemas.

Please, give me a reproducer to allow further digging.

**Comment by smhc** [comment] 2020-04-07 04:04
The following code reproduces the issue:

```java
import org.openapi4j.core.model.v3.OAI3;
import org.openapi4j.operation.validator.validation.OperationValidator;
import org.openapi4j.parser.OpenApi3Parser;
import org.openapi4j.parser.model.v3.OpenApi3;
import org.openapi4j.parser.model.v3.Operation;
import org.openapi4j.parser.model.v3.Path;
import org.openapi4j.schema.validator.ValidationContext;
import java.io.File;

public class main {
    public static void main(String[] args) throws Exception {

        File specFile = new File("./openapi.json");
        OpenApi3 api = new OpenApi3Parser().parse(specFile, false);

        ValidationContext<OAI3> validationContext = new ValidationContext<OAI3>(api.getContext());

        Path path = api.getPath("/v1/xxxx");
        Operation op = null;
        if(path.isRef()) {
            op = path.copy(validationContext.getContext(), true).getOperation("post");
        } else {
            op = path.getOperation("post");
        }
        OperationValidator validator = new OperationValidator(validationContext, api, path, op);
    }
}
```

With the following files:

openapi.json:
```json
{
  "openapi": "3.0.3",
  "info": {
    "description": "openapi test spec",
    "title": "xxx",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:80/api"
    }
  ],
  "paths": {
    "/v1/xxxx": {
      "$ref": "other_file.yaml#/paths/~1v1~1xxxx"
    }
  }
}
```

other_file.yaml:
```yaml
openapi: 3.0.3
info:
  description: x
  title: x
  version: '1.0'
servers:
  - url: 'http://localhost:80/api'
paths:
  /v1/xxxx:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/StringObjType'
                  - $ref: '#/components/schemas/DoubleObjType'
                discriminator:
                  propertyName: objectType
          #      mapping:
          #         string: '#/components/schemas/StringObjType'
          #         double: '#/components/schemas/DoubleObjType'
          #         base64: '#/components/schemas/Base64ObjType'
          description: conversion response
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/RequestType'
        description: conversion request
components:
  schemas:
    RequestType:
      properties:
        type:
          type: string
      required:
        - type
      type: object
    StringObjType:
      properties:
        value:
          type: string
        objectType:
          type: string
      required:
        - objectType
      type: object
    DoubleObjType:
      properties:
        value:
          type: number
          format: double
        objectType:
          type: string
      required:
        - objectType
      type: object

```

**Comment by llfbandit** [comment] 2020-04-07 13:45
Closing this and opened those two issues #91 and #93

**Closed by llfbandit** 2020-04-07 13:45 UTC
Labels: question

**Comment by smhc** [comment] 2020-06-05 02:22
The following workaround doesn't seem to work anymore with version 1.0:

```java
        if(path.isRef()) {
            op = path.copy(validationContext.getContext(), true).getOperation("post");
        } else {
            op = path.getOperation("post");
        }
```

Is there something else that should be done instead to get the valid Operation object when a path is a reference?

**Comment by llfbandit** [comment] 2020-06-05 14:01
You mean with `getMappedContent` method?
No, this method maps the content only once from the raw content and return cached version on further calls.

So now, your adapted code does the exactly the same as `copy(model, true)` in a more efficient way (by avoiding recursion and copy each time) but you have to be careful if Operation is a $ref too.
