### ISSUE TITLE
Mandatory element missing is not throwing error

### ISSUE THREAD

**Issue by bachi317** [openapi4j/openapi4j#153] opened 2020-11-02 00:03 UTC
**Version**  
1.0.4  

**Describe the bug**  
We have an api which has two elements in the POST. one is "createMetadata" that has few fields under it and the other "createInstruction" which is a oneOf type element with 4 objects under it. If I won't supply "createInstruction" in the payload the framework is not throwing a validation error that the element is missing.

**Expected behavior**  
A validation error with "createInstruction" element missing should be sent back. 

**Additional context**  
N/A 

**To Reproduce**  
1. Attached the swagger that we are using for the createAPI. Import that onto your local eclipse or equivalent environment.
2. Pass the below payload to the framework along with the above swagger.
{
  "createMetadata": {
    "initiatorReferenceId": "123",
    "type": "directCreate",
    "authNumber": "123456",
    "createDate": "2020-11-01",
    "individual": false,
    "createCount": 3,
    "numberOfSignatories": 1,
    "hashTotal": "345678"
  }
}
3. You should notice validation successful instead of a validation failure message. 

Let me know if you need any further details. 

**Reproducer**  
N/A
[CreateAPI.yaml.zip](https://github.com/openapi4j/openapi4j/files/5472069/CreateAPI.yaml.zip)

**Comment by llfbandit** [comment] 2020-11-02 14:36
I can't reproduce the issue. With the given input every thing is fine on my side.

**Comment by bachi317** [comment] 2020-11-02 20:54
Greetings,

    It is working fine as I was checking the validation results size to be greater than 0. Apologies.  But for types of payloads under createInstruction, validationResults is giving the below error "body.createInstruction: More than 1 schema is valid."

is that how it supposed to work? and do I need to ignore that message each time with oneOff scenario? Thanks.

**Comment by llfbandit** [comment] 2020-11-03 07:54
OneOf keyword stands for 'only one schema must be valid'. If you have multiple valid schemas, use AnyOf instead.
Closing the issue since this is not related to the tool.

**Closed by llfbandit** 2020-11-03 07:54 UTC
Labels: bug
